import { invoke } from "@tauri-apps/api/core";

export type NativeCommand =
  | "platform_snapshot"
  | "platform_reveal_main"
  | "platform_pick"
  | "extension_snapshot"
  | "extension_add_marketplace"
  | "extension_refresh_catalogs"
  | "extension_install_disabled"
  | "extension_enable"
  | "extension_disable"
  | "extension_stage_update"
  | "extension_activate_update"
  | "extension_rollback"
  | "extension_revoke"
  | "extension_revoke_key"
  | "extension_uninstall"
  | "extension_set_skill_enabled"
  | "extension_select_skill"
  | "extension_customize_skill"
  | "extension_review_hook"
  | "extension_load_skill"
  | "extension_publisher_link"
  | "foundation_snapshot"
  | "workspace_start_snapshot"
  | "conversation_snapshot"
  | "artifact_snapshot"
  | "artifact_run_terminal"
  | "artifact_terminal_stdin"
  | "artifact_terminal_resize"
  | "artifact_terminal_stop"
  | "artifact_terminal_ack_output"
  | "artifact_open_browser"
  | "artifact_navigate_browser"
  | "artifact_clear_browser_data"
  | "artifact_mount_browser"
  | "artifact_resize_browser"
  | "artifact_focus_native_browser"
  | "artifact_detach_browser"
  | "artifact_open_file"
  | "artifact_open_folder"
  | "artifact_focus"
  | "artifact_close_focus"
  | "artifact_begin_file_edit"
  | "artifact_update_file_draft"
  | "artifact_discard_file_draft"
  | "artifact_reject_file_proposal"
  | "artifact_resolve_file_conflict"
  | "artifact_save_file"
  | "artifact_answer_approval"
  | "artifact_refresh_folder"
  | "artifact_navigate_folder"
  | "artifact_select_folder_entry"
  | "artifact_reply"
  | "artifact_expand_context"
  | "conversation_attachment_preview"
  | "conversation_request_branch"
  | "conversation_answer_branch_approval"
  | "conversation_begin_pending"
  | "conversation_cancel_pending"
  | "conversation_update_draft"
  | "conversation_submit"
  | "conversation_cancel_attempt"
  | "conversation_retry_attempt"
  | "conversation_activate_session"
  | "conversation_activate_project"
  | "conversation_add_project"
  | "conversation_relocate_project"
  | "conversation_rename_project"
  | "conversation_copy_project_path"
  | "conversation_reveal_project"
  | "conversation_reorder_projects"
  | "conversation_inactivate_project"
  | "conversation_inactivate_session"
  | "runtime_core_snapshot"
  | "runtime_production_activate"
  | "runtime_production_shutdown"
  | "runtime_production_pump"
  | "runtime_production_answer_approval";

/**
 * The only renderer import of Tauri's generic invoke primitive. Product
 * adapters expose allowlisted commands and validate every returned payload.
 */
export function invokeNative(
  command: NativeCommand,
  args: Readonly<Record<string, unknown>>,
): Promise<unknown> {
  return invoke(command, args);
}
